### ISSUE TITLE
Error "Enabling" when a mouse trigger isn't present

### ISSUE THREAD

**Issue by DerrikCreates** [luttje/Key2Joy#27]
[Video showing process to replicate](https://user-images.githubusercontent.com/8542076/188338612-d6ebb513-8bc8-4e10-8281-8fa6dbeedd9e.mp4)

Error https://gist.github.com/DerrikCreates/d7f2b1937e4a6c4402e02ce1ef66eb7b

I've had some inconsistent problems with bindings now working after upgrading to 0.5.2.
Even after this error if I hit continue the biddings still seem to work but it might be the cause of my 
inconsistencies. I'm not sure if having a mouse trigger in the profile is the only "fix" but its the only one I've found.

**Comment by luttje** [comment]
Hey, thanks for reporting this!

The problem is clear to me. Without a mouse trigger something causes an error.

Good job on finding a workaround, but you're right that it's not a true fix.

I'm quite busy this week, but may find some time to fix this bug anyway. You can expect that before the end of the week.

Let me know if there's any other bugs or even features you're missing. I might be able to include them in the next version.

Thanks again 🙂

**Comment by luttje** [comment]
This is now fixed in [0.5.3](https://github.com/luttje/Key2Joy/releases/tag/0.5.3)

Have a nice day!
