### ISSUE TITLE
Feature request: Option to make clicking the "X" button actually exit the program

### ISSUE THREAD

**Issue by klsgh** [luttje/Key2Joy#45]
Ever so often when I want to quit Key2Joy I click on the red "X" button of the window (just out of habit), just to get prompted with the "Minimizing to notification tray" message. I then have to fiddle it out of the notification tray again and select "File/Exit Program". I know I can mute that message, but I'd rather prefer an option to not have it minimize to the notification tray at all, but just exit when I click "X".

**Comment by luttje** [comment]
Hi @klsgh,

Good point! It's a habit for me too to expect the program to close when pressing the 'X' button in the top right. I'll mark this for future improvement. Would be nice to have a User Configuration option that makes Key2Joy shut down instead of minimizing on close.

Thanks for making this issue, I'll work on it later this year.
