### ISSUE TITLE
Keyboard keys not working with game in background, while mouse-assigned keys function normally?

### ISSUE THREAD

**Issue by mozbas38** [luttje/Key2Joy#46]
It seems that in the eFootball 2024 game, the keyboard keys are not working when the game screen is not active, such as when on the desktop. However, mouse-assigned keys work fine regardless of whether the game screen is active or not. What do you think might be the reason for the keyboard keys not working? You can check this program on [KeyToJoy](https://github.com/LYGreen/KeyToJoy) and maybe you can understand the issue by examining its contents.

**Comment by luttje** [comment]
Hi, thanks for your report!

With a quick look at our Key2Joy source-code I assume the problem might lie here: https://github.com/luttje/Key2Joy/blob/2fc3fe3e1f6fe7646d0f2bde8057bb145cb145fc/Key2Joy/LowLevelInput/GlobalInputHook.cs#L154C49-L154C56

I believe that if the line `isInputHandled = eventArguments.Handled;` is removed it may work. I assume that because the BaseTtrigger handles the 'top-most window' (eFootball 2024 in your case) it doesn't go any further to other parts of the code.

If the above is true then this might be related to #43.

I'm not going to download that game right now and give it a try, but in the future I may. I'll mark this as a bug for future reference.

Thanks again for reporting it!

**Comment by mozbas38** [comment]
> Hi, thanks for your report!
> 
> With a quick look at our Key2Joy source-code I assume the problem might lie here: https://github.com/luttje/Key2Joy/blob/2fc3fe3e1f6fe7646d0f2bde8057bb145cb145fc/Key2Joy/LowLevelInput/GlobalInputHook.cs#L154C49-L154C56
> 
> I believe that if the line `isInputHandled = eventArguments.Handled;` is removed it may work. I assume that because the BaseTtrigger handles the 'top-most window' (eFootball 2024 in your case) it doesn't go any further to other parts of the code.
> 
> If the above is true then this might be related to #43.
> 
> I'm not going to download that game right now and give it a try, but in the future I may. I'll mark this as a bug for future reference.
> 
> Thanks again for reporting it!

I did as you said, but the problem still hasn't been resolved.

**Comment by luttje** [comment]
Hey there @mozbas38!

I finally had time to work on this project and I believe I've stumbled upon the same problem you had:

**If you're starting the game with 'Run as Administrator' (or it starts itself that way), then Key2Joy also needs to run as an Administrator to be able to send keyboard input to it.**

Are you running the game as admin? Does running Key2Joy as admin fix the problem for you?

Thanks for letting me know!

**Comment by luttje** [comment]
I'm going to close this issue for now, but feel free to reopen it if your problem remains. Please do check out a newer alpha (`0.7.0-alpha...`) build of this app ([link to releases](https://github.com/luttje/Key2Joy/releases)), it may have fixed the problem you were experiencing.

Thanks for your help!
