### ISSUE TITLE
GamePad.SimulateTrigger does not exist even though docs say it does

### ISSUE THREAD

**Issue by LinearNoodle** [luttje/Key2Joy#67]
![image](https://github.com/luttje/Key2Joy/assets/92155355/1de6fa0b-c1d8-4923-b4cf-608fa441a42a)
I'm just trying to add a simple script to convert shift + w to a half input trigger so you can accelerate slowly in certain games. I am an experienced Lua developer. After my own script didn't work I tried copy pasting the documentation example and it still gave the same error of SimulateTrigger being a nil value.

**Comment by luttje** [comment]
Hi there! Thanks for reporting this.

After a few tests it looks like there's a problem with how the arguments are converted. Or rather they aren't converted to the types they should be converted to. I'll see if I can fix this tonight.

**Comment by luttje** [comment]
I believe I've fixed the issues (there were several) for the example not working with this update: https://github.com/luttje/Key2Joy/releases/tag/0.7.0-alpha.606db1bb42

Please do note that there are other outstanding issues that may cause problems (e.g.: those being fixed in #66)

Feel free to re-open this issue if you still have problems. Thanks for reporting in.
